name: Build Kotlin APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 设置 JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        version: '17'

    # Checkout 代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 生成 Kotlin 项目
    - name: Generate Kotlin project
      run: |
        mkdir kotlin-example-app
        cd kotlin-example-app

        # 创建 settings.gradle
        cat > settings.gradle <<EOF
        pluginManagement {
            repositories {
                google()
                mavenCentral()
            }
        }

        dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories {
                google()
                mavenCentral()
            }
        }

        rootProject.name = "KotlinExampleApp"
        EOF

        # 创建 build.gradle
        cat > build.gradle <<EOF
        plugins {
            id 'com.android.application' version '8.1.2'
            id 'org.jetbrains.kotlin.android' version '1.9.10'
        }

        android {
            compileSdkVersion 33
            defaultConfig {
                applicationId "com.example.app"
                minSdkVersion 21
                targetSdkVersion 33
                versionCode 1
                versionName "1.0"
            }
            buildTypes {
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                }
            }
        }

        dependencies {
            implementation "androidx.core:core-ktx:1.12.0"
            implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.10"
        }
        EOF

        # 初始化 Gradle Wrapper
        gradle wrapper --gradle-version 8.1.1

    # 构建 APK
    - name: Build APK
      run: |
        cd kotlin-example-app
        ./gradlew assembleDebug

    # 推送生成的项目和 APK 文件
    - name: Push Generated Project and APK
      run: |
        cd kotlin-example-app
        git add .
        git commit -m "Add generated Kotlin project"
        git push

    # 上传 APK 文件到仓库
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: kotlin-example-app/app/build/outputs/apk/debug/app-debug.apk