name: Build and Deploy Kotlin App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    # Set up Kotlin project structure
    - name: Generate Kotlin project
      run: |
        mkdir -p kotlin-example-app/src/main/res/values
        # Ensure necessary directories are created, such as res/values for resources

    # Install Android SDK and dependencies
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        echo y | sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "extras;android;m2repository" "extras;google;m2repository"
    
    # Configure Gradle wrapper and dependencies
    - name: Configure Gradle wrapper
      run: ./gradlew wrapper --gradle-version 8.1.1 --distribution-type all

    # Build Kotlin project
    - name: Build Kotlin project
      run: |
        cd kotlin-example-app
        ./gradlew clean build

    # Upload APK artifact
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: kotlin-example-app/build/outputs/apk/debug/app-debug.apk

    # Checkout code for release process (optional if releasing the APK)
    - name: Checkout code again for release (optional)
      uses: actions/checkout@v3

    # Release APK (optional - you may want to deploy or upload it to a repository)
    - name: Release APK
      run: |
        # You can replace this with actual release steps (upload to Play Store, etc.)
        echo "Releasing APK..."

    # Finish
    - name: Publish Checkout code
      run: echo "Build completed successfully."