name: Generate, Build, and Push Kotlin App

on:
  push:
    branches:
      - main
  workflow_dispatch: # 支持手动触发工作流

jobs:
  generate-build-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 初始化环境并创建项目
      - name: Generate Kotlin project
        run: |
          mkdir kotlin-example-app
          cd kotlin-example-app

          # 创建 settings.gradle
          cat > settings.gradle <<EOF
          pluginManagement {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }
          rootProject.name = "KotlinExampleApp"
          EOF

          # 创建 build.gradle
          cat > build.gradle <<EOF
          plugins {
              id 'com.android.application' version '8.1.2'
              id 'kotlin-android' version '1.8.22'
          }

          android {
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.example.app"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
          }

          dependencies {
              implementation "androidx.core:core-ktx:1.12.0"
              implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
          }
          EOF

          # 创建应用程序主目录
          mkdir -p app/src/main/java/com/example/app
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values

          # 创建 MainActivity 文件
          cat > app/src/main/java/com/example/app/MainActivity.kt <<EOF
          package com.example.app

          import android.os.Bundle
          import androidx.appcompat.app.AppCompatActivity

          class MainActivity : AppCompatActivity() {
              override fun onCreate(savedInstanceState: Bundle?) {
                  super.onCreate(savedInstanceState)
                  setContentView(R.layout.activity_main)
              }
          }
          EOF

          # 创建 XML 布局文件
          cat > app/src/main/res/layout/activity_main.xml <<EOF
          <LinearLayout
              xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical"
              android:gravity="center">

              <TextView
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:text="Hello, Kotlin!" />
          </LinearLayout>
          EOF

          # 创建 strings.xml 文件
          cat > app/src/main/res/values/strings.xml <<EOF
          <resources>
              <string name="app_name">Kotlin Example App</string>
          </resources>
          EOF

      # 3. 构建 APK 文件
      - name: Build APK
        run: |
          cd kotlin-example-app
          ./gradlew assembleDebug
          cd ..

      # 4. 将生成的项目和 APK 推送到仓库
      - name: Push Generated Project and APK
        run: |
          # 解压和移动文件
          mkdir output
          mv kotlin-example-app/app/build/outputs/apk/debug/app-debug.apk output/

          # 添加并推送文件
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add kotlin-example-app output
          git commit -m "Add generated Kotlin project and APK"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}