jobs:
  generate-build-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 使用 actions/setup-java 安装 Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 使用 Temurin JDK
          java-version: '17'

      # 2. 检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. 初始化环境并生成项目
      - name: Generate Kotlin project
        run: |
          mkdir kotlin-example-app
          cd kotlin-example-app

          # 创建 settings.gradle
          cat > settings.gradle <<EOF
          pluginManagement {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }
          rootProject.name = "KotlinExampleApp"
          EOF

          # 创建 build.gradle
          cat > build.gradle <<EOF
          plugins {
              id 'com.android.application' version '8.1.2'
              id 'org.jetbrains.kotlin.android' version '1.9.10'
          }

          android {
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.example.app"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
          }

          repositories {
              google()
              mavenCentral()
          }

          dependencies {
              implementation "androidx.core:core-ktx:1.12.0"
              implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.10"
          }
          EOF

          # 初始化 Gradle Wrapper
          gradle wrapper --gradle-version 8.1.1

      # 4. 构建 APK
      - name: Build APK
        run: |
          cd kotlin-example-app
          chmod +x gradlew
          ./gradlew assembleDebug
          cd ..

      # 5. 推送生成的项目和 APK
      - name: Push Generated Project and APK
        run: |
          mkdir output
          mv kotlin-example-app/app/build/outputs/apk/debug/app-debug.apk output/

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add kotlin-example-app output
          git commit -m "Add generated Kotlin project and APK"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
