name: Kotlin Example App Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # 设置 java-version
        distribution: 'temurin'
        java-package: 'jdk'
        check-latest: false

    # Step 2: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 3: Generate Kotlin project
    - name: Generate Kotlin project
      run: |
        mkdir kotlin-example-app
        cd kotlin-example-app

        # Create settings.gradle
        cat > settings.gradle <<EOF
        pluginManagement {
          repositories {
            google()
            mavenCentral()
          }
        }
        dependencyResolutionManagement {
          repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
          repositories {
            google()
            mavenCentral()
          }
        }
        rootProject.name = "KotlinExampleApp"
        EOF

        # Create build.gradle
        cat > build.gradle <<EOF
        plugins {
          id 'com.android.application' version '8.1.2'
          id 'org.jetbrains.kotlin.android' version '1.9.10'
        }

        android {
          compileSdkVersion 33

          defaultConfig {
            applicationId "com.example.app"
            minSdkVersion 21
            targetSdkVersion 33
            versionCode 1
            versionName "1.0"
            namespace 'com.example.app' // Required namespace
          }

          buildTypes {
            release {
              minifyEnabled false
              proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
          }
        }

        dependencies {
          implementation "androidx.core:core-ktx:1.12.0"
          implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.10"
        }
        EOF

        # Initialize Gradle Wrapper
        gradle wrapper --gradle-version 8.1.1

    # Step 4: Build the project
    - name: Build Kotlin project
      run: |
        cd kotlin-example-app
        ./gradlew build

    # Step 5: Upload APK as Artifact
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kotlin-example-app-apk
        path: kotlin-example-app/app/build/outputs/apk/release/app-release.apk
